[build]
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "18"

# CORS 헤더 설정 (API 호출을 위해)
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 캐시 설정
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
